### ISSUE TITLE
KeyError: 'tair'

### ISSUE THREAD

**Issue by LDH-lin** [cchauve/ANGeS#6]
i have some problem when i use the master scripy 
this is my error
----> Started
----> Copying input
----> Filtering markers
----> Doubling markers
----> Markers: plant/MARKERS/9plant_MARKERS_DOUBLED
----> Cleaning ACS file
----> Computing species
------> All species: plant/ACS/9plant_SPECIES
----> Computing species pairs to compare
------> All informative pairs: plant/ACS/9plant_PAIRS
----> Computing ancestral contiguous sets: plant/ACS/9plant_ACS
------> Species: tair ys
--------> Computing maximum common intervals: plant/ACS/9plant_MCI_tair_ys
Traceback (most recent call last):
  File "/data/02_work/lindh/software/anges/anges_1.01/src/ACS/ACS_compute_common_intervals_unique.py", line 55, in <module>
    filtered_blocks = filter_markers(blocks, [spe1, spe2])
  File "/data/02_work/lindh/software/anges/anges_1.01/src/ACS/acs.py", line 111, in filter_markers
    for ch in blocks[spes[0]]:	
KeyError: 'tair'

--------> Computing strong common intervals: plant/ACS/9plant_SCI_tair_ys
Traceback (most recent call last):
  File "/data/02_work/lindh/software/anges/anges_1.01/src/ACS/ACS_compute_common_intervals_unique.py", line 55, in <module>
    filtered_blocks = filter_markers(blocks, [spe1, spe2])
  File "/data/02_work/lindh/software/anges/anges_1.01/src/ACS/acs.py", line 111, in filter_markers
    for ch in blocks[spes[0]]:	
KeyError: 'tair'

--------> Computing supported adjacencies: plant/ACS/9plant_SA_tair_ys
Traceback (most recent call last):
  File "/data/02_work/lindh/software/anges/anges_1.01/src/ACS/ACS_compute_supported_adjacencies_unique.py", line 45, in <module>
    filtered_blocks = filter_markers(blocks, [spe1, spe2])
  File "/data/02_work/lindh/software/anges/anges_1.01/src/ACS/acs.py", line 111, in filter_markers
    for ch in blocks[spes[0]]:	
KeyError: 'tair'

------> Joining ACS files: plant/ACS/9plant_ACS_tair_ys
Traceback (most recent call last):
  File "/data/02_work/lindh/software/anges/anges_1.01/src/ACS/ACS_join_files.py", line 44, in <module>
    in_matrix = open(sys.argv[i])		# matrix file
IOError: [Errno 2] No such file or directory: 'plant/ACS/9plant_MCI_tair_ys'

------> Joining ACS files: plant/ACS/9plant_ACS_tair_ys, plant/ACS/9plant_ACS
------> Species: tair xg
--------> Computing maximum common intervals: plant/ACS/9plant_MCI_tair_xg
Traceback (most recent call last):
  File "/data/02_work/lindh/software/anges/anges_1.01/src/ACS/ACS_compute_common_intervals_unique.py", line 55, in <module>
    filtered_blocks = filter_markers(blocks, [spe1, spe2])
  File "/data/02_work/lindh/software/anges/anges_1.01/src/ACS/acs.py", line 111, in filter_markers
    for ch in blocks[spes[0]]:	
KeyError: 'tair'

--------> Computing strong common intervals: plant/ACS/9plant_SCI_tair_xg
Traceback (most recent call last):
  File "/data/02_work/lindh/software/anges/anges_1.01/src/ACS/ACS_compute_common_intervals_unique.py", line 55, in <module>
    filtered_blocks = filter_markers(blocks, [spe1, spe2])
  File "/data/02_work/lindh/software/anges/anges_1.01/src/ACS/acs.py", line 111, in filter_markers
    for ch in blocks[spes[0]]:	
KeyError: 'tair'
and here is my data
>1
tqs.10:13054594-13058488 +
dz.10:14903386-14907226 +
tao.6:7122985-7126348 +
apple.3:10373862-10377221 +
apple.11:11933646-11937050 +
xigua.1:25797464-25801653 -
tair.2:15295853-15298362 -
tair.5:19604976-19606766 +
li.3:7886715-7889492 +
li.11:9651661-9654981 +
cm.3:27504030-27507560 -

>2
tqs.10:13039110-13046705 +
dz.10:14887840-14895503 +
tao.6:7105612-7113401 +
apple.11:11907889-11916311 +
apple.3:10342152-10350367 +
xigua.1:26023377-26034428 -
tair.2:15301699-15305786 -
li.11:9631601-9637432 +
li.3:7862941-7870809 +
ys.NC_037293.2:2496220-2504680 +
ys.NC_037293.2:2496218-2504680 +
ys.NC_037288.2:21737665-21749179 +
ys.NC_037288.2:21737664-21749510 +
ys.NC_037288.2:21737664-21749510 +
ys.NC_037288.2:21737664-21749179 +
cm.3:27520519-27525807 -

>3
tqs.10:12994817-12995347 +
dz.10:14836502-14837029 +
tao.6:7100147-7100653 +
apple.3:10334521-10335458 +
apple.11:11897669-11899213 +
xigua.2:34849622-34850131 +
xigua.1:26145586-26146095 -
tair.5:27561771-27563065 +
tair.3:19238160-19239645 -
tair.2:15310004-15311193 -
li.3:7857440-7858282 +
li.11:9621268-9622183 +
ys.NC_037288.2:21731518-21732418 +
ys.NC_037293.2:2455473-2456456 +
cm.3:27535861-27536376 -

>4
tqs.11:15392691-15393191 +
tqs.10:12950041-12950541 -
dz.10:14822751-14823251 -
dz.11:22913180-22913680 +
tao.6:7089743-7090243 -
tao.6:23918332-23918832 +
apple.11:11861470-11861970 -
apple.3:10318438-10320213 -
apple.4:17040905-17041405 +
xigua.2:34838833-34839333 -
xigua.4:23709394-23709894 -
xigua.10:33536938-33537438 +
tair.5:27556265-27557360 -
tair.2:18783453-18784403 -
tair.3:22490811-22492018 -
li.4:14068210-14069858 +
li.3:7844603-7845103 -
li.11:9572253-9574662 -
li.12:15362761-15363595 +
ys.NC_037290.2:5742521-5743239 +
ys.NC_037302.2:15025348-15025988 +
ys.NC_037302.2:15029339-15030061 +
ys.NC_037302.2:15120474-15121179 -
ys.NC_037302.2:15124508-15125217 -
cm.6:9911327-9912079 -
i will be very appreciate it if you could answer me

**Comment by cchauve** [comment]
Can you join all the input files and also the parameters file or the command line.
One thing I noticed is that in the markers you show the species names are not prefixed by ">" (i.e. ">1", ">2", ">3", ">4").

**Comment by LDH-lin** [comment]
it seems like the SpeciesTree problem ,when i use the example tree that i change the species ,it can be work ,
(tair:0.231555,((xg:0.33395,((tqs:0.0250969,dz:0.0297529):0.171896,(cm:0.175235,(tao:0.0770099,(apple:0.0158909,li:0.0187958):0.0901407):0.0430722):0.0872409):0.0427629):0.0482029,gj:0.
224907)@:0.231555);
it is my own species 
>1
tqs.TQS-Chr08:21137707-21138527 -
dz.Chr08:25444046-25444996 -
tao.G2:28916692-28917392 -
apple.Chr07:33480620-33481553 -
xg.Chr01:5604919-5606766 +
tair.Chr5:24373872-24374472 -
tair.Chr5:24373872-24374491 -
li.Chr01:23067503-23068665 -
li.Chr07:26691791-26692318 -

>2
tqs.TQS-Chr08:21135263-21137059 +
dz.Chr08:25441587-25443424 +
tao.G2:28913688-28916443 +
tao.G2:28913688-28916443 +
apple.Chr07:33477732-33480663 +
apple.Chr01:31831129-31834187 +
xg.Chr05:8349011-8352509 +
tair.Chr5:24371813-24373873 +
tair.Chr5:24371766-24373872 +
li.Chr07:26688605-26691739 +
li.Chr01:23065310-23067123 +
gj.chr9:29483087-29486425 +

>3
tqs.TQS-Chr08:21130776-21133501 -
dz.Chr08:25437066-25440598 -
xg.Chr01:5609295-5614294 +
tair.Chr5:24369379-24371591 -
tair.Chr5:24369324-24371531 -
tair.Chr5:24369324-24371448 -
li.Chr01:23061629-23063693 -
li.Chr07:26685165-26687118 -
gj.chr9:29478117-29479482 -

**Comment by cchauve** [comment]
I am sorry I do no understand and I do not have enough information to try to reproduce your problem. If you attach to your answer the exact files that you use, I can try.

**Comment by LDH-lin** [comment]
when i use this tree 
(((tqs:0.2,dz:0.2):0.2,(li:0.2,apple:0.2):0.2)@:0.6,xg:1);it can be useful
this tree can not be useful 
(((((((apple:0.0158909,li:0.0187958):0.0901407,tao:0.0770099):0.0430722,cm:0.175235):0.0872409,(tqs:0.0250969,dz:0.0297529):0.171896):0.0427629,xg:0.33395):0.0482029,gj:0.224907):0.2315
55,tair:0.231555)@;

**Comment by LDH-lin** [comment]
when i use this tree 
(((tqs:0.2,dz:0.2):0.2,(li:0.2,apple:0.2):0.2)@:0.6,xg:1);it can be useful
this tree can not be useful 
(((((((apple:0.0158909,li:0.0187958):0.0901407,tao:0.0770099):0.0430722,cm:0.175235):0.0872409,(tqs:0.0250969,dz:0.0297529):0.171896):0.0427629,xg:0.33395):0.0482029,gj:0.224907):0.2315
55,tair:0.231555)@;

**Comment by karthickbrlab** [comment]
HI..
CAN I KNOW WHAT WENT WRONG HERE..

python anges_CAR.py PARAMETERS_MONOCOTS_BAB 
  File "/home/ubuntu/Documents/ANGeS/src/MASTER/anges_CAR.py", line 42
    print string
    ^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by cchauve** [comment]
Hello
Did you use python2 or python3. ANGeS has been written for python2.
cedric chauve

**Comment by karthickbrlab** [comment]
Hi..

 I found lot of indent errors in the python script.

Is there any releases where I can get updated one

**Comment by karthickbrlab** [comment]
hi..


i have used UI version in linux.

**i couldn't SELECT the files..the error was**

ython anges_CAR_UI.py 
Selected file: /home/ubuntu/Documents/ANGeS/src/MASTER/kb
Exception in Tkinter callback
Traceback (most recent call last):
  **File "/home/ubuntu/anaconda3/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Documents/ANGeS/src/MASTER/anges_CAR_UI.py", line 68, in click
    ret = tkFileDialog.askopenfilename()
          ^^^^^^^^^^^^
**NameError: name 'tkFileDialog' is not defined****


**_**this the python script i used.**_**

import sys
import os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(sys.argv[0]))) + '/COMMON')

import bm	# for precision
import params

from tkinter import *
from tkinter import filedialog

file_path = filedialog.askopenfilename()
print(f"Selected file: {file_path}")
from tkinter import messagebox
import tkinter as tk
from tkinter import scrolledtext
import subprocess
import threading
import _thread
from io import StringIO



THANKS 
KARTHICK

**Comment by cchauve** [comment]
I do not understand. Maybe a version issue with the package tkinter. I would suggest to use the command-line vesion.
cedric chauve

**Comment by karthickbrlab** [comment]
python anges_CAR.py 
  File "/home/ubuntu/Documents/ANGeS/src/MASTER/anges_CAR.py", line 514
    file_list.append(ra + "_" + sp[0] + "_" + sp[1] + "_" + sp3)
TabError: inconsistent use of tabs and spaces in indentation


SHOULD I USE VIRTUAL ENV OF PYTHON 2

**Comment by karthickbrlab** [comment]
yeah.. Thank you..its working in Python 2 virtual env

**Comment by karthickbrlab** [comment]
hi..

Can i use the single copy orthologs from OrthoFinder as a marker??

**Comment by cchauve** [comment]
Yes, provided the coordinates of the markers do not overlap.
cedric chauve

**Comment by karthickbrlab** [comment]
can you please let me know what went wrong here..

----> Started
----> Copying input
----> Filtering markers
----> Markers: PROTO/MARKERS/PROTO_MARKERS
----> Cleaning ACS file
----> Computing species
------> All species: PROTO/ACS/PROTO_SPECIES
----> Computing species pairs to compare
------> All informative pairs: PROTO/ACS/PROTO_PAIRS
----> Computing ancestral contiguous sets: PROTO/ACS/PROTO_ACS
----> Weighting ACS: PROTO/WEIGHT/PROTO_WACS
----> Creating PQR-tree: PROTO/CARS/PROTO_PQRTREE
Traceback (most recent call last):
  File "/home/ubuntu/Documents/ANGeS/anges_1.01/src/C1P/C1P_compute_PQRtree.py", line 41, in <module>
    pqtree.make_PQR_tree(m).write(f.write)
  File "/home/ubuntu/Documents/ANGeS/anges_1.01/src/C1P/pqtree.py", line 231, in make_PQR_tree
    while len(og[0]._support) == 0:
IndexError: list index out of range


----> Computing PQ-tree using spectral seriation on correlation matrix
Traceback (most recent call last):
  File "/home/ubuntu/Documents/ANGeS/anges_1.01/src/SERIATION/SERIATION_compute_PQtree_correlation_matrix.py", line 71, in <module>
    for t in T:
TypeError: 'NoneType' object is not iterable

----> Done
Stopped




IN MARKERS FOLDER THE MARKER LIST IS INCOMPLETE.. THE FILTERED MARKERS ARE..
>1
Arabidopsis_thaliana.1:11648-13714 -

>2
Arabidopsis_thaliana.1:75582-76758 +

>3
Arabidopsis_thaliana.1:86514-88213 -

**Comment by cchauve** [comment]
Can you share the data you used?
cedric chauve

**Comment by karthickbrlab** [comment]
[SpeciesTree_PROTOBR.txt](https://github.com/user-attachments/files/18654297/SpeciesTree_PROTOBR.txt)
[MARKERS_PROTOBR.txt](https://github.com/user-attachments/files/18654296/MARKERS_PROTOBR.txt)

**Comment by karthickbrlab** [comment]
Hi..

Can i get some updates on the error.


Thanks

**Comment by cchauve** [comment]
There are two problems in the markers file:
- The species name for Diplotaxis erucoides is incorrect with a space after the "_" (it is written Diplotaxis_ erucoides, and once Diplotaxis_  erucoides)
- The markers contain overlap. For example, in Brassica_rapa, markers 1883 and 1884 overlap:
  >1883 Brassica_rapa.1:6009171-6013648 and >1884 Brassica_rapa.1:6013527-6016014

You can find all overlaps by running the command
python src/MARKERS/MARKERS_check_for_overlaps_markers.py MARKERS_PROTOBR.txt MARKERS_PROTOBR.overlap.txt
where the output file MARKERS_PROTOBR.overlap.txt will show a large number of overlaps

You need to fix the species name and preprocess the markers to remove overlaps.

cedric chauve

**Comment by karthickbrlab** [comment]
Thank you for the clarification Dr. Cedric

Karthick

**Comment by karthickbrlab** [comment]
HI.. Dr. Cedric.

Should I remove just marker of a species that is showing overlaps or the entire orthogroup/marker before further analysis?

**Comment by cchauve** [comment]
It is up to you. Dealing wit overlapping markers is the main issue with the ANGeS model and there is no standard way to deal with it. The key is that there are no overlapping markers. A single species will likely not contain all overlaps. An extreme approach is to remove all orthogroups involved in overlaps but in my experience it reduces significantly the number of orthogroups. A simpler (but not very principled)  approach is to first modify the coordinates of each marker (e.g. take the 2 middle bases: if a marker has coodinates 1000-2500 for example modify the coordinates to 1725-1726) and then discard orthogroups involved in overlaps if any remains.

**Comment by karthickbrlab** [comment]
HI..DR CEDRIC..

AFTER CHANGING THE MARKER NAMES AND FILTERING OVERLAPS, STILL THE MARKER FIELD IS EMPTY.. 

I checked again using Markers_check_for_overlaps.py..there were no overlaps. But when i try running anges the markers are empty in src/MASTER/MARKERS. When I used No filtering at universality.. the marker field shows 
>5
Arabidopsis_thaliana.1:114285-116108 +

>7
Arabidopsis_thaliana.1:164104-165517 -

>10
Arabidopsis_thaliana.1:306479-309109 -

>11
Arabidopsis_thaliana.1:319835-322860 -

>12
Arabidopsis_thaliana.1:347890-352480 +

>13
Arabidopsis_thaliana.1:352636-354969 -

I TRIED USING EXAMPLE DATA..ITS WORKING GOOD. I HERE ATTACH THE CORRECTED MARKER FILE..KINDLY LOOK INTO THIS

[PBR_fil_markers.txt](https://github.com/user-attachments/files/19906206/PBR_fil_markers.txt)

**Comment by karthickbrlab** [comment]
HI..DR CEDRIC.. Can I get any update on this?

AFTER CHANGING THE MARKER NAMES AND FILTERING OVERLAPS, STILL THE MARKER
FIELD IS EMPTY..

I checked again using Markers_check_for_overlaps.py..there were no
overlaps. But when i try running anges the markers are empty in
src/MASTER/MARKERS. When I used No filtering at universality.. the marker
field shows

5
Arabidopsis_thaliana.1:114285-116108 +

7
Arabidopsis_thaliana.1:164104-165517 -

10
Arabidopsis_thaliana.1:306479-309109 -

11
Arabidopsis_thaliana.1:319835-322860 -

12
Arabidopsis_thaliana.1:347890-352480 +

13
Arabidopsis_thaliana.1:352636-354969 -

I TRIED USING EXAMPLE DATA..ITS WORKING GOOD. I HERE ATTACH THE CORRECTED
MARKER FILE..KINDLY LOOK INTO THIS


I have attached the marker file in github issue we are discussing



Thank you

**Comment by cchauve** [comment]
My apologies.

I am away on vacations right now and will look into this when I am back.

cedric chauve

________________________________________

**Comment by karthickbrlab** [comment]
Thank you Dr. Cedric.

Can i expect some update from you?

Well. I need one more clarity..Which genomic feature other than orthologous genes could be suitable for anges?

**Comment by karthickbrlab** [comment]
Prof. cedric.

Any updates from your side will be very helpful

**Comment by cchauve** [comment]
Hello
Any feature (genomic marker) that is defined by genomic coordinates such that different markers do not overlap. Usually ANGeS is used with genes (but overlapping genes must be filtered out) or synteny blocks. But the key is to avoid overlapping coordinates otherwise, the order of markers is ambiguous.
